# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Jan Michalski

name: Pylint

on:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get install python3-gnucash
          pip install pylint
          pip install -r requirements.txt

      - name: Run pylint
        env:
          # E0401: Unable to import 'gnucash' (import-error)
          PYTHONPATH: /usr/lib/python3/dist-packages/
        run: |
          echo "Files to lint:"
          git ls-files *.py
          echo
          pylint --reports y $(git ls-files *.py) | tee pylint_output.txt

      - name: Print pylint output as notice
        if: always()
        run: |
          echo "::notice::$(sed -f .github/workflows/scripts/join_lines.sed pylint_output.txt)"
